### ISSUE TITLE
No screenshot image on project page.

### ISSUE THREAD

**Issue by okkhoy** [AY1920S1-CS2113-T14-3/main#151]
Check: https://nuscs2113-ay1920s1.github.io/website/admin/projectList.html#t14-3

Read:
![image](https://user-images.githubusercontent.com/1023494/68544376-7c957400-03fd-11ea-9336-3a7ee1cf4f6f.png)

**Comment by chelsea148629** [comment]
Uploaded Ui.png and moved team member photos.
Check: https://nuscs2113-ay1920s1.github.io/website/admin/projectList.html#t14-3
