### ISSUE TITLE
Empty textfile will cause GUI to not respond

### ISSUE THREAD

**Issue by njw95** [AY1920S1-CS2113-T14-3/main#88]
Make wordup.txt empty first, then on program launch, immediately do a search w/WORD

Will return errors in intelliJ and UI will not respond to that command.

Bug suspected to be due to **SearchCommand.java line 25 to 32 inclusive.** inside the try statement.

#87 

Refer to WordBank.java line 82 to 91 inclusive for implementation of searchWordMeaning function.

Error will not occur if there are data inside wordup.txt (at least one line) on startup or user uses ADDCOMMAND before using search (on any word not present in dictionary)

**Comment by tessa-z** [comment]
Does the program throw any error messages in the console?

**Comment by chelsea148629** [comment]
Change SearchCommand.java line 25 to 32 to calling the AddCommand directly.
Delete `Word temp = new Word(word, result); wordBank.put(word, temp);` in WorkBank.java, searchWordMeaning(), around line 90, which avoids to add word in bank before calling, so the AddCommand can work.

**Comment by chelsea148629** [comment]
> Does the program throw any error messages in the console?

I'm cleaning up the code and will create a pr later!

**Comment by tessa-z** [comment]
> Change SearchCommand.java line 25 to 32 to calling the AddCommand directly.
> Delete `Word temp = new Word(word, result); wordBank.put(word, temp);` in WorkBank.java, searchWordMeaning(), around line 90, which avoids to add word in bank before calling, so the AddCommand can work.

I don't think the error is due to this tho, it's the part where wordCount searched in the treemap if it contains key. If the treemap is empty it will have some null exception that's probably why it died.

I can edit it after you do a pr :) or if u can find it just edit it also can!

**Comment by tessa-z** [comment]
> > Change SearchCommand.java line 25 to 32 to calling the AddCommand directly.
> > Delete `Word temp = new Word(word, result); wordBank.put(word, temp);` in WorkBank.java, searchWordMeaning(), around line 90, which avoids to add word in bank before calling, so the AddCommand can work.
> 
> I don't think the error is due to this tho, it's the part where wordCount searched in the treemap if it contains key. If the treemap is empty it will have some null exception that's probably why it died.
> 
> I can edit it after you do a pr :) or if u can find it just edit it also can!

Wait I can edit it on my end first and integrate with yours later

**Comment by tessa-z** [comment]
Solved it!

**Comment by chelsea148629** [comment]
Yep your right I find something wrong!
